apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-rp
spec:
  selector:
    matchLabels:
      app: nginx-rp
  template:
    metadata:
      labels:
        app: nginx-rp
    spec:
      containers:
      - name: nginx-rp-contianer
        image: nginx:latest
        volumeMounts:
          - name: conf-vol
            mountPath: "/etc/nginx/conf.d"
            readOnly: true
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80

      volumes:
        - name: conf-vol
          configMap:
            name: nginx-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: nginxrp-svc
spec:
  type: NodePort
  selector:
    app: nginx-rp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
