pipeline{
    
    environment{
        
        registry = "partha00011/app1"
        registryCredential = 'dockerhub-account'
        dockerImage = ''
        
    }
    
    agent any
    
    stages{
        
        stage('Cloning the repository'){
            
            steps{
                git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/parthaSdeb/devops-challange-project.git'
            }
        }
        
        stage('Creating docker image for app1'){
            
            steps{
                dir('app1/src'){
                    script{
                         
                         dockerImage = docker.build registry + ":$BUILD_NUMBER"
                    }
                }
            }
        }
        
        stage('push docker image to dockerhub'){
            steps{
                script {
                    
                    docker.withRegistry( '', registryCredential ){
                        dockerImage.push()
                    }
                }
            }
        }
        
        stage('Deploy the application'){
            steps{
                dir('app1/deploy') {
                    
                    sh "sed -i s,partha00011/app1,partha00011/app1:${BUILD_NUMBER},g app1-deployment.yaml"
                    
                    sh "kubectl apply -f app1-deployment.yaml"
                    
                    sh "kubectl apply -f app1-svc.yaml"
                    
                    
                }
            }
        }
        
        
        
    }
}
